# For the complete configuration, please visit
# https://www.contentful.com/developers/docs/php/tutorials/getting-started-with-contentful-and-symfony/
contentful:
    delivery:
        main:
            token: "%env(CONTENTFUL_ACCESS_TOKEN)%"
            space: "%env(CONTENTFUL_SPACE_ID)%"
