netgen_layouts:
    pagelayout: 'base.html.twig'
    value_types:
        doctrine_screencast:
            name: 'Screencast'
            manual_items: false
    query_types:
        screencast_query:
            name: 'Screencasts'
