netgen_layouts:
    pagelayout: 'base.html.twig'
    value_types:
        doctrine_screencast:
            name: 'Screencast'
            manual_items: true
    query_types:
        screencast_query:
            name: 'Screencasts'

    view:
        item_view:
            # "app" defines templates used in the admin
            app:
                this_key_is_meaningless:
                    template: "layouts/admin/screencast.html.twig"
                    match:
                        # must match the "value_types" value
                        item\value_type: doctrine_screencast
            # "default" defines templates used in the frontend
            default:
                this_key_is_meaningless:
                    template: "layouts/frontend/screencast.html.twig"
                    match:
                        item\value_type: doctrine_screencast
